import { PostMatchViewModel } from '../../src/lib/aoe4/analysis/postMatchViewModel';

export function makeMvpModelFixture(): PostMatchViewModel {
  return {
    header: {
      mode: 'Ranked 1v1',
      durationLabel: '10:00',
      map: 'Dry Arabia',
      summaryUrl: 'https://aoe4world.com/players/111/games/123456?sig=testsig',
      youCivilization: 'English',
      opponentCivilization: 'French',
      outcome: 'Defeated 10:00',
    },
    deferredBanner: null,
    metricCards: {
      finalPoolDelta: 148,
      ageAnalyses: [
        {
          age: 'Dark',
          startTime: 0,
          endTime: 120,
          timeRangeLabel: '0:00-2:00',
          gapSummary: 'Gap widened: Tied -> You +148.',
          allocationSummary: 'Allocation: your edge was Technology +100; Military was similar.',
          destructionSummary: 'Destruction: neither player destroyed measurable value.',
          conversionSummary: 'Meaning: No major conversion signal inside this shared window.',
          summary: 'Gap widened: Tied -> You +148. Allocation: your edge was Technology +100; Military was similar. Destruction: neither player destroyed measurable value. Meaning: No major conversion signal inside this shared window.',
        },
        {
          age: 'Feudal',
          startTime: 120,
          endTime: 420,
          timeRangeLabel: '2:00-7:00',
          gapSummary: 'Gap held: You +148 -> You +148.',
          allocationSummary: 'Allocation: no major allocation difference.',
          destructionSummary: 'Destruction: neither player destroyed measurable value.',
          conversionSummary: 'Meaning: No major conversion signal inside this shared window.',
          summary: 'Gap held: You +148 -> You +148. Allocation: no major allocation difference. Destruction: neither player destroyed measurable value. Meaning: No major conversion signal inside this shared window.',
        },
        {
          age: 'Castle',
          startTime: 420,
          endTime: 600,
          timeRangeLabel: '7:00-10:00',
          gapSummary: 'Gap held: You +148 -> You +148.',
          allocationSummary: 'Allocation: no major allocation difference.',
          destructionSummary: 'Destruction: neither player destroyed measurable value.',
          conversionSummary: 'Meaning: No major conversion signal inside this shared window.',
          summary: 'Gap held: You +148 -> You +148. Allocation: no major allocation difference. Destruction: neither player destroyed measurable value. Meaning: No major conversion signal inside this shared window.',
        },
        {
          age: 'Imperial',
          startTime: null,
          endTime: null,
          timeRangeLabel: 'No shared window',
          gapSummary: 'Only you reached Imperial, so there was no shared Imperial window to compare.',
          allocationSummary: 'You reached Imperial; opponent did not.',
          destructionSummary: 'No shared window to evaluate destruction.',
          conversionSummary: 'No shared window to evaluate conversion.',
          summary: 'Only you reached Imperial, so there was no shared Imperial window to compare.',
        },
      ],
      castleAgeDeltaSeconds: 30,
      yourBet: {
        label: 'balanced',
        subtitlePercent: 34,
        economicPercent: 31,
        militaryPercent: 34,
      },
      opponentBet: {
        label: 'balanced',
        subtitlePercent: 35,
        economicPercent: 30,
        militaryPercent: 35,
      },
    },
    trajectory: {
      durationSeconds: 600,
      yAxisMax: 1000,
      youSeries: [{
        timestamp: 0,
        economic: 50,
        populationCap: 0,
        militaryCapacity: 0,
        militaryActive: 168,
        defensive: 0,
        research: 100,
        advancement: 500,
        total: 818,
      }],
      opponentSeries: [{
        timestamp: 0,
        economic: 50,
        populationCap: 0,
        militaryCapacity: 0,
        militaryActive: 120,
        defensive: 0,
        research: 100,
        advancement: 400,
        total: 670,
      }],
      adjustedMilitarySeries: [{
        timestamp: 0,
        you: 202,
        opponent: 132,
        delta: 70,
        youRawMilitaryActive: 168,
        opponentRawMilitaryActive: 120,
        youCounterAdjustedMilitaryActive: 183.27,
        opponentCounterAdjustedMilitaryActive: 125.71,
        youUpgradeMultiplier: 1.1,
        opponentUpgradeMultiplier: 1.05,
        youUnitBreakdown: [],
        opponentUnitBreakdown: [],
      }],
      youBandItemDeltas: [{
        timestamp: 0,
        band: 'economic',
        itemKey: 'unit:villager',
        itemLabel: 'Villager',
        deltaValue: 50,
        deltaCount: 1,
      }],
      opponentBandItemDeltas: [],
      hoverSnapshots: [{
        timestamp: 0,
        timeLabel: '0:00',
        markers: [],
        you: {
          economic: 50,
          populationCap: 0,
          militaryCapacity: 0,
          militaryActive: 168,
          defensive: 0,
          research: 100,
          advancement: 500,
          total: 818,
        },
        opponent: {
          economic: 50,
          populationCap: 0,
          militaryCapacity: 0,
          militaryActive: 120,
          defensive: 0,
          research: 100,
          advancement: 400,
          total: 670,
        },
        delta: {
          economic: 0,
          populationCap: 0,
          militaryCapacity: 0,
          militaryActive: 48,
          defensive: 0,
          research: 0,
          advancement: 100,
          total: 148,
        },
        gather: {
          you: 500,
          opponent: 480,
          delta: 20,
        },
        villagerOpportunity: {
          you: {
            timestamp: 0,
            cumulativeLoss: 90,
            cumulativeResourcesGained: 1000,
            cumulativeResourcesPossible: 1090,
          },
          opponent: {
            timestamp: 0,
            cumulativeLoss: 140,
            cumulativeResourcesGained: 900,
            cumulativeResourcesPossible: 1040,
          },
        },
        adjustedMilitary: {
          you: 202,
          opponent: 132,
          delta: 70,
          youRaw: 168,
          opponentRaw: 120,
          youCounterAdjusted: 183.27,
          opponentCounterAdjusted: 125.71,
          youCounterMultiplier: 1.091,
          opponentCounterMultiplier: 1.048,
          youUpgradeMultiplier: 1.1,
          opponentUpgradeMultiplier: 1.05,
          youPct: 20,
          opponentPct: 10,
          youUnitBreakdown: [],
          opponentUnitBreakdown: [],
        },
        bandBreakdown: {
          economic: {
            you: [{ label: 'Villager', value: 50, percent: 100, count: 1 }],
            opponent: [],
          },
          populationCap: { you: [], opponent: [] },
          militaryCapacity: { you: [], opponent: [] },
          militaryActive: { you: [], opponent: [] },
          defensive: { you: [], opponent: [] },
          research: { you: [], opponent: [] },
          advancement: { you: [], opponent: [] },
          opportunityLost: {
            you: [{ label: '0:00-0:30', value: 90, percent: 100, count: 1 }],
            opponent: [{ label: '0:00-0:30', value: 140, percent: 100, count: 2 }],
          },
        },
        accounting: {
          you: {
            economic: 50,
            populationCap: 0,
            militaryCapacity: 0,
            militaryActive: 168,
            defensive: 0,
            research: 100,
            advancement: 500,
            destroyed: 0,
            float: 500,
            gathered: 1318,
            total: 818,
          },
          opponent: {
            economic: 50,
            populationCap: 0,
            militaryCapacity: 0,
            militaryActive: 120,
            defensive: 0,
            research: 100,
            advancement: 400,
            destroyed: 0,
            float: 1000,
            gathered: 1670,
            total: 670,
          },
          delta: {
            economic: 0,
            populationCap: 0,
            militaryCapacity: 0,
            militaryActive: 48,
            defensive: 0,
            research: 0,
            advancement: 100,
            destroyed: 0,
            float: -500,
            gathered: -352,
            total: 148,
          },
        },
      }],
      ageMarkers: [],
    },
    gatherRate: {
      durationSeconds: 600,
      youSeries: [{ timestamp: 0, ratePerMin: 500 }],
      opponentSeries: [{ timestamp: 0, ratePerMin: 480 }],
    },
    villagerOpportunity: {
      targetVillagers: 120,
      resourceSeries: {
        you: [{
          timestamp: 0,
          cumulativeLoss: 90,
          cumulativeResourcesGained: 1000,
          cumulativeResourcesPossible: 1090,
        }],
        opponent: [{
          timestamp: 0,
          cumulativeLoss: 140,
          cumulativeResourcesGained: 900,
          cumulativeResourcesPossible: 1040,
        }],
      },
      context: {
        you: {
          totalResourcesGathered: 1000,
          totalPossibleResources: 1250,
          cumulativeLoss: 250,
          lossShareOfPossible: 0.2,
          damageDealtToOpponent: 120,
          damageDealtToOpponentPossible: 960,
          damageDealtToOpponentShare: 0.125,
          netEcoSwing: -130,
        },
        opponent: {
          totalResourcesGathered: 900,
          totalPossibleResources: 1080,
          cumulativeLoss: 180,
          lossShareOfPossible: 1 / 6,
          damageDealtToOpponent: 60,
          damageDealtToOpponentPossible: 1060,
          damageDealtToOpponentShare: 60 / 1060,
          netEcoSwing: -120,
        },
      },
      you: {
        baselineRateRpm: 40,
        targetVillagers: 120,
        upgradeEvents: [],
        series: [{
          timestamp: 0,
          expectedVillagerRateRpm: 40,
          expectedVillagers: 0,
          producedVillagers: 10,
          aliveVillagers: 9,
          underproductionDeficit: 0,
          deathDeficit: 0,
          totalDeficit: 0,
          underproductionLossPerMin: 0,
          deathLossPerMin: 0,
          totalLossPerMin: 0,
          cumulativeUnderproductionLoss: 0,
          cumulativeDeathLoss: 0,
          cumulativeTotalLoss: 0,
        }],
      },
      opponent: {
        baselineRateRpm: 40,
        targetVillagers: 120,
        upgradeEvents: [],
        series: [{
          timestamp: 0,
          expectedVillagerRateRpm: 40,
          expectedVillagers: 0,
          producedVillagers: 0,
          aliveVillagers: 0,
          underproductionDeficit: 0,
          deathDeficit: 0,
          totalDeficit: 0,
          underproductionLossPerMin: 0,
          deathLossPerMin: 0,
          totalLossPerMin: 0,
          cumulativeUnderproductionLoss: 0,
          cumulativeDeathLoss: 0,
          cumulativeTotalLoss: 0,
        }],
      },
    },
    events: [{
      id: 'timing-1',
      timestamp: 100,
      phase: 'Feudal',
      category: 'Timing',
      description: 'Example',
      score: 1,
      magnitude: 1,
    }],
    oneLineStory: 'Example story',
  };
}
