import { StaticDataCache } from '../../src/lib/aoe4/types';

const zeroStats = {
  ekills: 0,
  edeaths: 0,
  sqprod: 0,
  sqlost: 0,
  bprod: 0,
  upg: 0,
  totalcmds: 0,
};

const zeroScores = { total: 0, military: 0, economy: 0, technology: 0, society: 0 };
const zeroTotals = { food: 0, gold: 0, stone: 0, wood: 0, total: 0 };
const resources = {
  timestamps: [0, 61, 100, 200, 253, 275, 333, 355, 415, 1254, 1344, 1613, 2505, 2600],
  food: Array(14).fill(0),
  gold: Array(14).fill(0),
  stone: Array(14).fill(0),
  wood: Array(14).fill(0),
  foodPerMin: Array(14).fill(0),
  goldPerMin: Array(14).fill(0),
  stonePerMin: Array(14).fill(0),
  woodPerMin: Array(14).fill(0),
  total: Array(14).fill(0),
  military: Array(14).fill(0),
  economy: Array(14).fill(0),
  technology: Array(14).fill(0),
  society: Array(14).fill(0),
};

export function makeUnknownBucketSummary() {
  return {
    gameId: 876543,
    winReason: 'Surrender',
    mapName: 'Dry Arabia',
    mapBiome: 'Desert',
    leaderboard: 'rm_1v1',
    duration: 2600,
    startedAt: 0,
    finishedAt: 2600,
    players: [
      {
        profileId: 111,
        name: 'Unknown Buckets',
        civilization: 'ayyubids',
        team: 1,
        apm: 0,
        result: 'win',
        _stats: zeroStats,
        actions: {
          feudalAge: [275],
          upgradeAddCultureWingDarkBAbbHa01: [275],
        },
        scores: zeroScores,
        totalResourcesGathered: zeroTotals,
        totalResourcesSpent: zeroTotals,
        resources,
        buildOrder: [
          {
            id: '11254893',
            icon: 'icons/races/abbasid_historic/upgrades/society',
            pbgid: 2141107,
            type: 'Upgrade',
            finished: [275],
            constructed: [],
            destroyed: [],
            unknown: {},
          },
          {
            id: '11119584',
            icon: 'icons/hud/age/age_display_persistent_2',
            pbgid: 108171,
            type: 'Age',
            finished: [],
            constructed: [],
            destroyed: [],
            unknown: { '10': [275] },
          },
          {
            id: '11191836',
            icon: 'icons/races/campaign/units/camel_trader',
            pbgid: 2762454,
            type: 'Unit',
            finished: [],
            constructed: [],
            destroyed: [],
            unknown: { '14': [100, 200] },
          },
          {
            id: '11160584',
            icon: 'icons/races/chinese/units/imperial_official',
            pbgid: 2631059,
            type: 'Unit',
            finished: [],
            constructed: [],
            destroyed: [],
            unknown: { '14': [0, 253, 333] },
          },
          {
            id: '11265429',
            icon: 'icons/races/templar/units/pilgrim',
            pbgid: 5000301,
            type: 'Unit',
            finished: [],
            constructed: [],
            destroyed: [],
            unknown: { '15': [355, 415] },
          },
          {
            id: '11254919',
            icon: 'icons/races/abbasid_historic/units/tower_of_the_sultan',
            pbgid: 2141356,
            type: 'Unit',
            finished: [],
            constructed: [1145],
            destroyed: [],
            unknown: { '6': [1344] },
          },
          {
            id: '11142995',
            icon: 'icons/races/common/units/ram',
            pbgid: 8635755,
            type: 'Unit',
            finished: [],
            constructed: [1128],
            destroyed: [],
            unknown: { '6': [1254] },
          },
          {
            id: '11258380',
            icon: 'icons/races/common/units/mangonel',
            pbgid: 7804932,
            type: 'Unit',
            finished: [],
            constructed: [1442],
            destroyed: [],
            unknown: { '6': [1613] },
          },
          {
            id: '11245398',
            icon: 'icons/races/byzantine/units/chierosiphon',
            pbgid: 2140765,
            type: 'Unit',
            finished: [],
            constructed: [],
            destroyed: [],
            unknown: { '6': [2505] },
          },
        ],
      },
      {
        profileId: 222,
        name: 'Opponent',
        civilization: 'english',
        team: 2,
        apm: 0,
        result: 'loss',
        _stats: zeroStats,
        actions: {},
        scores: zeroScores,
        totalResourcesGathered: zeroTotals,
        totalResourcesSpent: zeroTotals,
        resources,
        buildOrder: [],
      },
    ],
  };
}

export function makeUnknownBucketStaticData(): StaticDataCache {
  return {
    fetchedAt: new Date().toISOString(),
    units: [],
    buildings: [],
    technologies: [
      {
        id: 'feudal-culture-wing-logistics-1',
        name: 'Logistics (Feudal Culture Wing)',
        baseId: 'feudal-culture-wing-logistics',
        pbgid: 2141107,
        civs: ['ay'],
        costs: { food: 400, gold: 200 },
        classes: ['abbasid_wing_upgrade', 'age_up_upgrade'],
        age: 1,
        icon: 'icons/races/abbasid_historic/upgrades/society',
      },
    ],
  };
}
