import fs from 'fs';
import path from 'path';
import { StaticDataCache } from '../../packages/aoe4-core/src/types';

export function makeUnknownBucketMechanicsFixture(): any {
  const fixturePath = path.resolve(__dirname, '../fixtures/sampleGameSummary.json');
  const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'));

  fixture.gameId = 876543;
  fixture.duration = 2600;
  fixture.players[0] = {
    ...fixture.players[0],
    profileId: 111,
    name: 'Unknown Buckets',
    civilization: 'ayyubids',
    actions: {
      feudalAge: [275],
      upgradeAddCultureWingDarkBAbbHa01: [275],
    },
    resources: {
      ...fixture.players[0].resources,
      timestamps: [
        0, 61, 100, 200, 253, 275, 308, 323, 333, 338, 342, 353,
        355, 393, 415, 416, 466, 546, 1134, 1254, 1344, 1613, 2505, 2600,
      ],
    },
    buildOrder: [
      {
        id: '11254893',
        icon: 'icons/races/abbasid_historic/upgrades/society',
        pbgid: 2141107,
        type: 'Upgrade',
        finished: [275],
        constructed: [],
        destroyed: [],
        unknown: {},
      },
      {
        id: '11119584',
        icon: 'icons/hud/age/age_display_persistent_2',
        pbgid: 108171,
        type: 'Age',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '10': [275] },
      },
      {
        id: '11191836',
        icon: 'icons/races/campaign/units/camel_trader',
        pbgid: 2762454,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '14': [100, 200] },
      },
      {
        id: '11160584',
        icon: 'icons/races/chinese/units/imperial_official',
        pbgid: 2631059,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '14': [0, 253, 333] },
      },
      {
        id: '11265429',
        icon: 'icons/races/templar/units/pilgrim',
        pbgid: 5000301,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '15': [355, 415] },
      },
      {
        id: '11254919',
        icon: 'icons/races/abbasid_historic/units/tower_of_the_sultan',
        pbgid: 2141356,
        type: 'Unit',
        finished: [],
        constructed: [1145],
        destroyed: [],
        unknown: { '6': [1344] },
      },
      {
        id: '11142995',
        icon: 'icons/races/common/units/ram',
        pbgid: 8635755,
        type: 'Unit',
        finished: [],
        constructed: [1128],
        destroyed: [],
        unknown: { '6': [1254] },
      },
      {
        id: '11258380',
        icon: 'icons/races/common/units/mangonel',
        pbgid: 7804932,
        type: 'Unit',
        finished: [],
        constructed: [1442],
        destroyed: [],
        unknown: { '6': [1613] },
      },
      {
        id: '11245398',
        icon: 'icons/races/byzantine/units/chierosiphon',
        pbgid: 2140765,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '6': [2505] },
      },
      {
        id: '11266336',
        icon: 'icons/races/sengoku/units/yatai',
        pbgid: 9001316,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: {
          '14': [61],
          '15': [523],
        },
      },
      {
        id: '11218702',
        icon: 'icons/races/malian/buildings/pit_mine',
        pbgid: 2076058,
        type: 'Building',
        finished: [],
        constructed: [390],
        destroyed: [],
        unknown: {},
      },
      {
        id: '11143387',
        icon: 'icons/races/mongols/buildings/ger',
        pbgid: 181324,
        type: 'Building',
        finished: [],
        constructed: [370],
        destroyed: [],
        unknown: {},
      },
      {
        id: '11200458',
        icon: 'icons/races/mongols/buildings/building_ovoo_mon',
        pbgid: 2074857,
        type: 'Building',
        finished: [],
        constructed: [380],
        destroyed: [],
        unknown: {},
      },
      {
        id: '11171906',
        icon: 'icons/races/common/units/fishing_boat',
        pbgid: 193121,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '14': [308, 342, 393, 466] },
      },
      {
        id: '11143609',
        icon: 'icons/races/common/units/trade_cart',
        pbgid: 132306,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '14': [323] },
      },
      {
        id: '11143609',
        icon: 'icons/races/common/units/trade_cart',
        pbgid: 2123482,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: {
          '14': [338, 353, 416, 546],
          '15': [1134],
        },
      },
      {
        id: '11270094',
        icon: 'icons/races/common/units/trade_cart',
        pbgid: 9003449,
        type: 'Unit',
        finished: [],
        constructed: [],
        destroyed: [],
        unknown: { '15': [1139] },
      },
    ],
  };

  return fixture;
}

export function makeUnknownBucketStaticDataCache(): StaticDataCache {
  return {
    fetchedAt: new Date().toISOString(),
    units: [
      {
        id: 'fishing-boat-2',
        name: 'Fishing Boat',
        baseId: 'fishing-boat',
        pbgid: 193121,
        civs: ['fr'],
        costs: { wood: 75 },
        classes: ['naval_fishing_ship', 'naval_unit', 'ship', 'worker'],
        displayClasses: ['Fishing Ship'],
        age: 2,
        icon: 'icons/races/common/units/fishing_boat',
      },
      {
        id: 'trader-2',
        name: 'Trader',
        baseId: 'trader',
        pbgid: 132306,
        civs: ['fr'],
        costs: { wood: 60, gold: 60 },
        classes: ['trade_cart', 'worker'],
        displayClasses: ['Trader'],
        age: 2,
        icon: 'icons/races/common/units/trade_cart',
      },
    ],
    buildings: [],
    technologies: [
      {
        id: 'feudal-culture-wing-logistics-1',
        name: 'Logistics (Feudal Culture Wing)',
        baseId: 'feudal-culture-wing-logistics',
        pbgid: 2141107,
        civs: ['ay'],
        costs: { food: 400, gold: 200 },
        classes: ['abbasid_wing_upgrade', 'age_up_upgrade'],
        age: 1,
        icon: 'icons/races/abbasid_historic/upgrades/society',
      },
    ],
  };
}
